pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = 'github-token-123' // Use the correct Jenkins credentials ID
    }

    stages {
        stage('Checkout Code') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.GIT_CREDENTIALS_ID, usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')]) {
                    sh 'git clone https://$GIT_USER:$GIT_TOKEN@github.com/Shivanipillalolu/your-repo.git'
                }
            }
        }
    }
}

