pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                    sh 'git clone https://$GITHUB_TOKEN@github.com/Shivanipillalolu/java-maven-app.git'
                }
            }
        }
    }
}


